# Generated by Django 5.0.4 on 2024-04-21 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='temp_id',
            field=models.CharField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
