# Generated by Django 5.0.4 on 2025-09-15 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_temp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="temp_id",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="packet",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
