# Generated by Django 5.0.4 on 2025-09-15 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_temp_id_alter_packet_sub_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="temp_id",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=36, null=True, unique=True
            ),
        ),
    ]
